=== yatusabebeibe/118LMSGIProyectoLMSGI/examen/Ex2ev-01/02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="objeto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>

                            <xs:element name="mesa">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="xs:string"/>
                                        <xs:element name="localizacion" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="ordenador">
                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="procesador">
                                            <xs:complexType>
                                                <xs:simpleContent >
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="fabricante" default="Intel">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="Intel"/>
                                                                    <xs:enumeration value="AMD"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="memoria">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:int">
                                                        <xs:attribute name="unidad" type="xs:string" fixed="Gb"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="discoduro">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:int">
                                                        <xs:attribute name="tamano" default="Gb">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="Tb|Gb|Mb"></xs:pattern>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                    </xs:sequence>          
                                </xs:complexType>           
                            </xs:element>                   
                        </xs:choice>                        

                        <xs:attribute name="codigo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Za-z]{2}\d{4}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yatusabebeibe/118LMSGIProyectoLMSGI/examen/Ex2ev-01/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE inventario SYSTEM "02.dtd"> -->
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02.xsd">
    <objeto codigo="MM2809">
        <mesa>
            <tipo>Oficina</tipo>
            <localizacion>B09</localizacion>
        </mesa>
    </objeto>
    <objeto codigo="PC2807">
        <ordenador>
            <procesador fabricante="Intel">
                i3
            </procesador>
            <memoria unidad="Gb">2</memoria>
            <discoduro tamano="Gb">520</discoduro>
        </ordenador>
    </objeto>
</inventario>
