=== yatusabebeibe/118LMSGIProyectoLMSGI/examen/Ex03/input/pedidos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tractor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="componente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fechaEntrega" minOccurs="0">
                                            <xs:complexType>
                                                <xs:attribute name="mes" type="xs:int"/>
                                                <xs:attribute name="anio" type="xs:gYear"/>
                                                <xs:attribute name="dia" type="xs:int" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="fragil" minOccurs="0"/>
                                        <xs:element name="peso">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:positiveInteger">
                                                        <xs:attribute name="unidad" >
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="k?g"></xs:pattern>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="numeroSerie" type="xs:string"/>
                                        <xs:element name="kmMaximos" type="xs:positiveInteger" minOccurs="0"/>
                                        <xs:element name="cantidad" type="xs:positiveInteger" default="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="referencia">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <xs:pattern value="[A-Z]{3}[0-9]{7}"></xs:pattern>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigoFabricante">
                            <xs:simpleType>
                                <xs:restriction base="xs:ID">
                                    <xs:pattern value="F[0-9]{3}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="idPedido">
                <xs:simpleType>
                    <xs:restriction base="xs:ID">
                        <xs:pattern value="P[0-9]{3}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="fecha" type="xs:date"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yatusabebeibe/118LMSGIProyectoLMSGI/examen/Ex03/input/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido idPedido="P002" fecha="2025-04-01"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidos.xsd" >
    <tractor codigoFabricante="F001">
        <componente referencia="CMP0000001">
            <fechaEntrega mes="04" anio="2025"/>
            <peso unidad="g">300</peso>
            <numeroSerie>SN111111111</numeroSerie>
            <kmMaximos>200000</kmMaximos>
            <cantidad>1</cantidad>
        </componente>
        <componente referencia="CMP0000002">
            <peso unidad="g">300</peso>
            <numeroSerie>SN111111112</numeroSerie>
            <cantidad>2</cantidad>
        </componente>
        <componente referencia="CMP0000003">
            <peso unidad="g">150</peso>
            <numeroSerie>SN111111113</numeroSerie>
            <kmMaximos>250000</kmMaximos>
            <cantidad>1</cantidad>
        </componente>
        <componente referencia="CMP0000004">
            <peso unidad="g">300</peso>
            <numeroSerie>SN111111114</numeroSerie>
            <kmMaximos>100000</kmMaximos>
            <cantidad>4</cantidad>
        </componente>
        <componente referencia="CMP0000005">
            <peso unidad="g">150</peso>
            <numeroSerie>SN111111115</numeroSerie>
            <kmMaximos>100000</kmMaximos>
            <cantidad>1</cantidad>
        </componente>
    </tractor>
    <tractor codigoFabricante="F012">
        <componente referencia="CMP0000006">
            <fechaEntrega mes="05" anio="2025" dia="10"/>
            <peso unidad="kg">1</peso>
            <numeroSerie>SN222222221</numeroSerie>
            <cantidad>1</cantidad>
        </componente>
        <componente referencia="CMP0000007">
            <fragil/>
            <peso unidad="kg">20</peso>
            <numeroSerie>SN222222222</numeroSerie>
            <kmMaximos>100000</kmMaximos>
            <cantidad>1</cantidad>
        </componente>
        <componente referencia="CMP0000008">
            <fragil/>
            <peso unidad="kg">25</peso>
            <numeroSerie>SN222222223</numeroSerie>
            <cantidad>1</cantidad>
        </componente>
        <componente referencia="CMP0000009">
            <fragil/>
            <peso unidad="kg">30</peso>
            <numeroSerie>SN222222224</numeroSerie>
            <cantidad>4</cantidad>
        </componente>
        <componente referencia="CMP0000010">
            <peso unidad="g">105</peso>
            <numeroSerie>SN222222225</numeroSerie>
            <cantidad>1</cantidad>
        </componente>
    </tractor>
</pedido>
