=== yatusabebeibe/118LMSGIProyectoLMSGI/unidad4/02/02.dtd
<!ELEMENT biblioteca (libro+)>
    <!ELEMENT libro (titulo, autores, año)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autores (autor+)>
            <!ELEMENT autor (nombre, apellido, nacionalidad)>
                <!ELEMENT nombre (#PCDATA)>
                <!ELEMENT apellido (#PCDATA)>
                <!ELEMENT nacionalidad (#PCDATA)>
        <!ELEMENT año (#PCDATA)>

        <!ATTLIST libro idLibro ID #REQUIRED>
        <!ATTLIST libro genero CDATA #IMPLIED>
        <!ATTLIST libro idioma CDATA "Español">
        <!ATTLIST libro formato (impreso|digital) "impreso">
        <!ATTLIST libro ref IDREF #IMPLIED>

=== yatusabebeibe/118LMSGIProyectoLMSGI/unidad4/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "02.dtd">


<biblioteca>
    <libro idLibro="libro1" genero="novela" >
        <titulo>BRRRR</titulo>
        <autores>
            <autor>
                <nombre>Yoni</nombre>
                <apellido>el lovo</apellido>
                <nacionalidad>Republica Dominicana</nacionalidad>
            </autor>
        </autores>
        <a単o>2024 beibe</a単o>
    </libro>
    <libro idLibro="libro2" genero="novela">
        <titulo>RRAAAAA</titulo>
        <autores>
            <autor>
                <nombre>Kebin</nombre>
                <apellido>el roneante</apellido>
                <nacionalidad>Indocumentao</nacionalidad>
            </autor>
        </autores>
        <a単o>2024 beibe</a単o>
    </libro>
</biblioteca>
